### ISSUE TITLE
Fix crash in beamformer when no data is available

### ISSUE THREAD

**Issue by jrs65** [radiocosmology/draco#133]
On days where there is no data available (e.g. CSD=2214) the daily pipeline will run and not do anything *except* the `BeamFormCat` task which crashes as the `.epoch` attribute hasn't been set (as it derives from the data).

```
Traceback (most recent call last):
  File "/home/jrs65/chime_pipeline_stable/code/caput/caput/scripts/runner.py", line 430, in <module>
    cli()
  File "/project/rpp-chime/chime/chime_env/modules/chime/python/2021.03/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/project/rpp-chime/chime/chime_env/modules/chime/python/2021.03/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/project/rpp-chime/chime/chime_env/modules/chime/python/2021.03/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/project/rpp-chime/chime/chime_env/modules/chime/python/2021.03/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/project/rpp-chime/chime/chime_env/modules/chime/python/2021.03/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jrs65/chime_pipeline_stable/code/caput/caput/scripts/runner.py", line 148, in run
    P.run()
  File "/project/6003614/chime/chime_processed/daily/rev_03/code/caput/caput/pipeline.py", line 603, in run
    out = task._pipeline_next()
  File "/project/6003614/chime/chime_processed/daily/rev_03/code/caput/caput/pipeline.py", line 1038, in _pipeline_next
    out = self.next(*args)
  File "/project/6003614/chime/chime_processed/daily/rev_03/code/draco/draco/core/task.py", line 319, in next
    output = self.process(*input)
  File "/project/6003614/chime/chime_processed/daily/rev_03/code/draco/draco/analysis/beamform.py", line 695, in process
    self._process_catalog(source_cat)
  File "/project/6003614/chime/chime_processed/daily/rev_03/code/draco/draco/analysis/beamform.py", line 611, in _process_catalog
    catalog["position"]["ra"], catalog["position"]["dec"], self.epoch
AttributeError: 'BeamFormCat' object has no attribute 'epoch'
```

**Comment by anjakefala** [comment]
For this bug, we are going to do a minor bandaid of logging a warning and then returning None in the process method if no actual data was supplied to the setup method.

**Comment by anjakefala** [comment]
Rick had started the work for this in this PR, and I decided to continue it there: https://github.com/radiocosmology/draco/pull/130
